### ISSUE TITLE
Write data to a more convenient format

### ISSUE THREAD

**Issue by benjamintd** [mapbox/graph-normalizer#32]
For now, we are writing a large number of files at the z14 level (which contain line-delimited GeoJSON features).

Dealing with those files can be slow and may cause problems with too many open file descriptors.

There can be another way of organizing this data. For instance, we could write those ways in a sqlite database; something along the lines of a [`mbtiles`](https://github.com/mapbox/mbtiles-spec/blob/master/1.1/spec.md) file with GeoJSON data inside, just like the format that Tippecanoe outputs.

We could be using [node-sqlite](https://github.com/mapbox/node-sqlite3) directly to write those, or take advantage of the existing utilities that [node-mbtiles](https://github.com/mapbox/node-mbtiles) or [Tippecanoe](https://github.com/mapbox/tippecanoe) provide in some way.

cc @morganherlocker @ericfischer @aaronlidman

**Comment by morganherlocker** [comment]
graph-normalizer no longer handles writing to disk. The user is free to implement whatever they would like.
