### ISSUE TITLE
Error trying to `npm install`

### ISSUE THREAD

**Issue by batpad** [mapbox/graph-normalizer#41]
Get the following error when trying to `npm install @mapbox/graph-normalizer`:

```
$ npm install @mapbox/graph-normalizer
npm WARN package.json tmp@1.0.0 No description
npm WARN package.json tmp@1.0.0 No repository field.
npm WARN package.json tmp@1.0.0 No README data
npm WARN engine @mapbox/graph-normalizer@3.0.2: wanted: {"node":"4.4.3"} (current: {"node":"4.4.5","npm":"2.15.5"})
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/sanjaybhangar/.nvm/versions/node/v4.4.5/bin/node" "/Users/sanjaybhangar/.nvm/versions/node/v4.4.5/bin/npm" "install" "@mapbox/graph-normalizer"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path /Users/sanjaybhangar/mapbox/tmp/node_modules/@mapbox/graph-normalizer/bin/normalize-ways
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/sanjaybhangar/mapbox/tmp/node_modules/@mapbox/graph-normalizer/bin/normalize-ways'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sanjaybhangar/mapbox/tmp/npm-debug.log
```

Node version: v4.4.5
Npm version: 2.15.5

This seems to be specific to `v3.0.1` or `v3.0.2` - installing `v3.0.0` works fine.

**Comment by MateoV** [comment]
`npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/sanjaybhangar/mapbox/tmp/node_modules/@mapbox/graph-normalizer/bin/normalize-ways'`

This file no longer exists but is still referenced in the [package.json](https://github.com/mapbox/graph-normalizer/blob/ef5b83f2f08ee27dd6131e20e71787d4f95609a0/package.json)

/cc @morganherlocker @xianny

**Comment by MateoV** [comment]
Note that this executable _does_ exist in 3.0.0 which is confusing.

**Comment by xianny** [comment]
3.0.0 was published a while ago in an unrelated commit. It was too long ago to unpublish, so I bumped patch versions. Going forward, the intention is to deprecate the CLI. Should we bump to 4.x.x so it's less confusing?

@MateoV currently the most updated version of graph-normalizer that supports the CLI is 2.3.4. Yes it is confusing sorry 😓

**Comment by xianny** [comment]
Removed outdated bin and bumped to 3.0.3.
