### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by morganherlocker** [mapbox/graph-normalizer#55]
👋 This library is open source, but does not include an open source license, which I believe is unintentional. Any chance a LICENSE file could be added under ISC or MIT to clear up any ambiguity around usage as a dependency?

cc @nickcordella @kuanb @angelanavarro

**Comment by angelanavarro** [comment]
👋 thanks for the headsup @morganherlocker, working on it!

**Comment by kuanb** [comment]
Fixed via https://github.com/mapbox/graph-normalizer/commit/9f059b82d58577a1d676137178b2045ba2844a59

**Comment by morganherlocker** [comment]
Thanks! 🙇‍♀
