### ISSUE TITLE
NPM Release

### ISSUE THREAD

**Issue by ingalls** [mapbox/graph-normalizer#59]
@kuanb Hey thanks a ton for all the work you've been doing on this library! Mind bumping the version and pushing a release to npm?

cc/ @nickcordella

**Comment by kuanb** [comment]
new npm release here: https://www.npmjs.com/package/@mapbox/graph-normalizer/v/3.1.2
new version: https://github.com/mapbox/graph-normalizer/commit/a073772b23e6ed1475040315d2faab5c38c4d097
